/**
 * @File               : ActorHelper_Test
 * @Description        : Test class for ActorHelper class methods
 * @Author             : Yassine RAZAQ (yrazaq@salesforce.com)
 * @Group              : 
 * @Last_Modified_On   : 21/10/2022
 * @Modification_Log   :
 *======================================================================================
 * Ver         Date                           Author                  Modification
 *======================================================================================
 * 1.0      21/10/2022                   Yassine RAZAQ               Initial version
 **/
@isTest
public class ActorHelper_Test {

    @testsetup
    static void testsetup() {

    }

    @isTest
    static void _Test() {
        // getting data

        // start test
        Test.startTest();

        Test.stopTest();
        // Asserting 
        System.assert(true, true);
    }
}